using Game.Contollers;
using Reflex.Core;
using UnityEngine;

//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game
{
	public class ControllersInstaller : MonoBehaviour, IInstaller
    {
		public void InstallBindings(ContainerBuilder containerBuilder)
        {
			Normal(containerBuilder);
		}

		private void Normal(ContainerBuilder containerBuilder)
		{
			// 0123
			containerBuilder.AddSingleton(typeof(TestController), typeof(TestController));	// 0123
		}	
    }
}