using Game.Controllers;
using Reflex.Core;
using UnityEngine;
using GameLoop.Interfaces;

//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Installers
{
	public class ControllersInstaller : MonoBehaviour, IInstaller
    {
		public void InstallBindings(ContainerBuilder containerBuilder)
        {
			Normal(containerBuilder);
		}

		private void Normal(ContainerBuilder containerBuilder)
		{
			// 0250
			containerBuilder.AddSingleton(typeof(PlayerMovementController), typeof(IController));	// 0250
			containerBuilder.AddSingleton(typeof(PlayerLookController), typeof(IController));	// 0255
		}	
    }
}